export const APP_ONLINE = "APP_ONLINE";

export const SETTINGS_CHANGE = "SETTINGS_CHANGE";

export const CIRCLE_FETCH_START = "CIRCLE_FETCH_START";
export const AREA_FETCH_START = "AREA_FETCH_START";

// 排名
export const RANK_SEARCH_USER_BY_NAME = "SEARCH_USER_BY_NAME";
export const RANK_SEARCH_USER_BY_COLLEGE = "SEARCH_USER_BY_COLLEGE";
export const RANK_SEARCH_USER_BY_MAJOR = "SEARCH_USER_BY_MAJOR";

// 粉丝
export const ADD_FAN = "ADD_FAN";
export const DELETE_FAN = "DELETE_FAN";
export const UPDATE_FANS = "UPDATE_FANS";
export const ADD_FANS = "ADD_FANS"; // 分页添加
export const CLEAR_FANS = "CLEAR_FANS";

// 关注
export const ADD_WATCH = "ADD_WATCH";
export const CANCEL_WATCH = "CANCEL_WATCH";
export const UPDATE_WATCHES = "UPDATE_WATCHES";
export const ADD_WATCHES = "ADD_WATCHES"; // 分页添加
export const CLEAR_WATCHES = "CLEAR_WATCHES";
export const UPDATE_WATCHES_ALL = "UPDATE_WATCHES_ALL";

// 排名关注榜单
export const UPDATE_RANK_WATCHES = "UPDATE_RANK_WATCHES";
export const ADD_RANK_WATCHES = "ADD_RANK_WATCHES"; // 分页添加


// TOP榜单
export const UPDATE_TOP = "UPDATE_TOP";
// PEER榜单
export const UPDATE_PEER = "UPDATE_PEER";
// 进步榜单
export const UPDATE_PROGRESS = "UPDATE_PROGRESS";
// 推荐用户名单
export const UPDATE_RECOMMEND = "UPDATE_RECOMMEND";

// 动态
export const UPDATE_DYNAMIC_COUNT = "UPDATE_DYNAMIC_COUNT";
export const RESET_DYNAMIC_COUNT = "RESET_DYNAMIC_COUNT";

//打卡
export const PUNCH_MORNING = "PUNCH_MORNING";
export const PUNCH_READING = "PUNCH_READING";
export const PUNCH_CERT = "PUNCH_CERT";
export const PUNCH_SKILL = "PUNCH_SKILL";

// 职么力
export const UPDATE_TASK_TOTAL_TREND_CHART_DATA = "UPDATE_TASK_TOTAL_TREND_CHART_DATA";
export const UPDATE_TASK_TOTAL_CHART_DATA = "UPDATE_TASK_TOTAL_CHART_DATA";
export const UPDATE_POWER_TREND_CHART_DATA = "UPDATE_POWER_TREND_CHART_DATA";
export const UPDATE_SALARY_INCREASE_RECORD_CHART_DATA = "UPDATE_SALARY_INCREASE_RECORD_CHART_DATA";

// 安全区
export const INIT_SAFE_AREA_INSETS = "INIT_SAFE_AREA_INSETS";
// 状态栏颜色
export const SET_STATUS_BAR_BACKGROUND_COLOR = "SET_STATUS_BAR_BACKGROUND_COLOR";

// 我关注的人的动态
export const UPDATE_NEWS_OF_WATCHES = "UPDATE_NEWS_OF_WATCHES";
export const ADD_NEWS_OF_WATCHES = "ADD_NEWS_OF_WATCHES";
